
package com.strongkey.skfs.soapstubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "soap", targetNamespace = "http://soap.skfs.strongauth.com/", wsdlLocation = "https://fido-poc.strongkey.com:8181/skfs/soap?wsdl")
public class Soap
    extends Service
{

    private final static URL SOAP_WSDL_LOCATION;
    private final static WebServiceException SOAP_EXCEPTION;
    private final static QName SOAP_QNAME = new QName("http://soap.skfs.strongauth.com/", "soap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://fido-poc.strongkey.com:8181/skfs/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAP_WSDL_LOCATION = url;
        SOAP_EXCEPTION = e;
    }

    public Soap() {
        super(__getWsdlLocation(), SOAP_QNAME);
    }

    public Soap(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAP_QNAME, features);
    }

    public Soap(URL wsdlLocation) {
        super(wsdlLocation, SOAP_QNAME);
    }

    public Soap(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAP_QNAME, features);
    }

    public Soap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Soap(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SKFSServlet
     */
    @WebEndpoint(name = "SKFSServletPort")
    public SKFSServlet getSKFSServletPort() {
        return super.getPort(new QName("http://soap.skfs.strongauth.com/", "SKFSServletPort"), SKFSServlet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SKFSServlet
     */
    @WebEndpoint(name = "SKFSServletPort")
    public SKFSServlet getSKFSServletPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.skfs.strongauth.com/", "SKFSServletPort"), SKFSServlet.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAP_EXCEPTION!= null) {
            throw SOAP_EXCEPTION;
        }
        return SOAP_WSDL_LOCATION;
    }

}
