/**
* Copyright StrongAuth, Inc. All Rights Reserved.
*
* Use of this source code is governed by the GNU Lesser General Public License v2.1
* The license can be found at https://github.com/StrongKey/fido2/blob/master/LICENSE
*
 *
 * $Date$
 * $Revision$
 * $Author$
 * $URL$
 *
 * *********************************************
 *                    888
 *                    888
 *                    888
 *  88888b.   .d88b.  888888  .d88b.  .d8888b
 *  888 "88b d88""88b 888    d8P  Y8b 88K
 *  888  888 888  888 888    88888888 "Y8888b.
 *  888  888 Y88..88P Y88b.  Y8b.          X88
 *  888  888  "Y88P"   "Y888  "Y8888   88888P'
 *
 * *********************************************
 *
 */

package com.strongauth.skfews.u2f.soap.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "soap", targetNamespace = "http://soap.u2f.skfews.strongauth.com/", wsdlLocation = "https://deiskce04.strongauth.com/skfe/soap?wsdl")
public class Soap
    extends Service
{

    private final static URL SOAP_WSDL_LOCATION;
    private final static WebServiceException SOAP_EXCEPTION;
    private final static QName SOAP_QNAME = new QName("http://soap.u2f.skfews.strongauth.com/", "soap");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://deiskce04.strongauth.com/skfe/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAP_WSDL_LOCATION = url;
        SOAP_EXCEPTION = e;
    }

    public Soap() {
        super(__getWsdlLocation(), SOAP_QNAME);
    }

    public Soap(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAP_QNAME, features);
    }

    public Soap(URL wsdlLocation) {
        super(wsdlLocation, SOAP_QNAME);
    }

    public Soap(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAP_QNAME, features);
    }

    public Soap(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Soap(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns SKFEServlet
     */
    @WebEndpoint(name = "SKFEServletPort")
    public SKFEServlet getSKFEServletPort() {
        return super.getPort(new QName("http://soap.u2f.skfews.strongauth.com/", "SKFEServletPort"), SKFEServlet.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SKFEServlet
     */
    @WebEndpoint(name = "SKFEServletPort")
    public SKFEServlet getSKFEServletPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.u2f.skfews.strongauth.com/", "SKFEServletPort"), SKFEServlet.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAP_EXCEPTION!= null) {
            throw SOAP_EXCEPTION;
        }
        return SOAP_WSDL_LOCATION;
    }

}
