
package com.strongkey.saka.web;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "StrongKeyLiteException", targetNamespace = "http://web.strongkeylite.strongauth.com/")
public class StrongKeyLiteException_Exception
    extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StrongKeyLiteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public StrongKeyLiteException_Exception(String message, StrongKeyLiteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public StrongKeyLiteException_Exception(String message, StrongKeyLiteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.strongauth.saka.web.StrongKeyLiteException
     */
    public StrongKeyLiteException getFaultInfo() {
        return faultInfo;
    }

}
