//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 09:53:09 AM PST 
//


package com.strongkey.skce.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.strongauth.skce.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.strongauth.skce.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SKCEEncryptionKeyInfoType }
     * 
     */
    public SKCEEncryptionKeyInfoType createSKCEEncryptionKeyInfoType() {
        return new SKCEEncryptionKeyInfoType();
    }

    /**
     * Create an instance of {@link SKCEServiceInfoType }
     * 
     */
    public SKCEServiceInfoType createSKCEServiceInfoType() {
        return new SKCEServiceInfoType();
    }

    /**
     * Create an instance of {@link SKCEAuthorizationInfoType }
     * 
     */
    public SKCEAuthorizationInfoType createSKCEAuthorizationInfoType() {
        return new SKCEAuthorizationInfoType();
    }

    /**
     * Create an instance of {@link SKCEInputFileInfoType }
     * 
     */
    public SKCEInputFileInfoType createSKCEInputFileInfoType() {
        return new SKCEInputFileInfoType();
    }

    /**
     * Create an instance of {@link SKCEStorageInfoType }
     * 
     */
    public SKCEStorageInfoType createSKCEStorageInfoType() {
        return new SKCEStorageInfoType();
    }

}
