//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 09:53:09 AM PST 
//


package com.strongkey.skce.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Information related to the input file that must be processed
 *                 by the SKCE's webservices 
 *             
 * 
 * <p>Java class for SKCEInputFileInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SKCEInputFileInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="filename" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEFileNameType"/>
 *         &lt;element name="filedigest" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEFileDigestType" minOccurs="0"/>
 *         &lt;element name="filedigestalgo" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEFileDigestAlgorithmType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SKCEInputFileInfoType", propOrder = {
    "filename",
    "filedigest",
    "filedigestalgo"
})
public class SKCEInputFileInfoType {

    @XmlElement(required = true)
    protected String filename;
    protected String filedigest;
    protected String filedigestalgo;

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the filedigest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiledigest() {
        return filedigest;
    }

    /**
     * Sets the value of the filedigest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiledigest(String value) {
        this.filedigest = value;
    }

    /**
     * Gets the value of the filedigestalgo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiledigestalgo() {
        return filedigestalgo;
    }

    /**
     * Sets the value of the filedigestalgo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiledigestalgo(String value) {
        this.filedigestalgo = value;
    }

}
