//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 09:53:09 AM PST 
//


package com.strongkey.skce.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Information about ciphertext file storage
 *             
 * 
 * <p>Java class for SKCEStorageInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SKCEStorageInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="storetype" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudStorageType"/>
 *         &lt;element name="cloudtype" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudStorageType" minOccurs="0"/>
 *         &lt;element name="cloudname" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudNameType" minOccurs="0"/>
 *         &lt;element name="accesskey" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudAccessKeyType" minOccurs="0"/>
 *         &lt;element name="secretkey" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudSecretKeyType" minOccurs="0"/>
 *         &lt;element name="cloudcontainer" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudContainerType" minOccurs="0"/>
 *         &lt;element name="cloudcredentialid" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCECloudCredentialIdentifierType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SKCEStorageInfoType", propOrder = {
    "storetype",
    "cloudtype",
    "cloudname",
    "accesskey",
    "secretkey",
    "cloudcontainer",
    "cloudcredentialid"
})
public class SKCEStorageInfoType {

    @XmlElement(required = true)
    protected String storetype;
    protected String cloudtype;
    protected String cloudname;
    protected String accesskey;
    protected String secretkey;
    protected String cloudcontainer;
    protected String cloudcredentialid;

    /**
     * Gets the value of the storetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStoretype() {
        return storetype;
    }

    /**
     * Sets the value of the storetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStoretype(String value) {
        this.storetype = value;
    }

    /**
     * Gets the value of the cloudtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudtype() {
        return cloudtype;
    }

    /**
     * Sets the value of the cloudtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudtype(String value) {
        this.cloudtype = value;
    }

    /**
     * Gets the value of the cloudname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudname() {
        return cloudname;
    }

    /**
     * Sets the value of the cloudname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudname(String value) {
        this.cloudname = value;
    }

    /**
     * Gets the value of the accesskey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccesskey() {
        return accesskey;
    }

    /**
     * Sets the value of the accesskey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccesskey(String value) {
        this.accesskey = value;
    }

    /**
     * Gets the value of the secretkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecretkey() {
        return secretkey;
    }

    /**
     * Sets the value of the secretkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecretkey(String value) {
        this.secretkey = value;
    }

    /**
     * Gets the value of the cloudcontainer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudcontainer() {
        return cloudcontainer;
    }

    /**
     * Sets the value of the cloudcontainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudcontainer(String value) {
        this.cloudcontainer = value;
    }

    /**
     * Gets the value of the cloudcredentialid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloudcredentialid() {
        return cloudcredentialid;
    }

    /**
     * Sets the value of the cloudcredentialid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloudcredentialid(String value) {
        this.cloudcredentialid = value;
    }

}
