//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 09:53:09 AM PST 
//


package com.strongkey.skce.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Information related to service credentials and related metadata
 *                 to access the SKCE's webservices
 *             
 * 
 * <p>Java class for SKCEServiceInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SKCEServiceInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="did" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEDidType"/>
 *         &lt;element name="svcusername" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEServiceUsernameType"/>
 *         &lt;element name="svcpassword" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEServicePasswordType"/>
 *         &lt;element name="protocol" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEProtocolType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SKCEServiceInfoType", propOrder = {
    "did",
    "svcusername",
    "svcpassword",
    "protocol"
})
public class SKCEServiceInfoType {

    protected int did;
    @XmlElement(required = true)
    protected String svcusername;
    @XmlElement(required = true)
    protected String svcpassword;
    @XmlElement(required = true)
    protected String protocol;

    /**
     * Gets the value of the did property.
     * 
     */
    public int getDid() {
        return did;
    }

    /**
     * Sets the value of the did property.
     * 
     */
    public void setDid(int value) {
        this.did = value;
    }

    /**
     * Gets the value of the svcusername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcusername() {
        return svcusername;
    }

    /**
     * Sets the value of the svcusername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcusername(String value) {
        this.svcusername = value;
    }

    /**
     * Gets the value of the svcpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvcpassword() {
        return svcpassword;
    }

    /**
     * Sets the value of the svcpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvcpassword(String value) {
        this.svcpassword = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocol(String value) {
        this.protocol = value;
    }

}
