//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.15 at 09:53:09 AM PST 
//


package com.strongkey.skce.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Information about the 'end-user' requesting services from the
 *                 SKCE, including any digital signature authorizations if required
 *             
 * 
 * <p>Java class for SKCEAuthorizationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SKCEAuthorizationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="userdn" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEUserDNType" minOccurs="0"/>
 *         &lt;element name="username" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEUsernameType" minOccurs="0"/>
 *         &lt;element name="authgroups" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCEAuthorizedGroupsType" minOccurs="0"/>
 *         &lt;element name="requiredauthorization" type="{http://xml.strongauth.com/schema/SKCEXMLSchema}SKCERequiredAuthorizationType" minOccurs="0"/>
 *         &lt;element name="payload" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SKCEAuthorizationInfoType", propOrder = {
    "userdn",
    "username",
    "authgroups",
    "requiredauthorization",
    "payload"
})
public class SKCEAuthorizationInfoType {

    protected String userdn;
    protected String username;
    protected String authgroups;
    protected Integer requiredauthorization;
    protected String payload;

    /**
     * Gets the value of the userdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserdn() {
        return userdn;
    }

    /**
     * Sets the value of the userdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserdn(String value) {
        this.userdn = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the authgroups property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthgroups() {
        return authgroups;
    }

    /**
     * Sets the value of the authgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthgroups(String value) {
        this.authgroups = value;
    }

    /**
     * Gets the value of the requiredauthorization property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequiredauthorization() {
        return requiredauthorization;
    }

    /**
     * Sets the value of the requiredauthorization property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequiredauthorization(Integer value) {
        this.requiredauthorization = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayload(String value) {
        this.payload = value;
    }

}
