
package com.strongkey.skfs.soapstubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SKFSServlet", targetNamespace = "http://soap.skfs.strongauth.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SKFSServlet {


    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.AuthenticateResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/authenticateRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/authenticateResponse")
    public String authenticate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authorize", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Authorize")
    @ResponseWrapper(localName = "authorizeResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.AuthorizeResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/authorizeRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/authorizeResponse")
    public String authorize(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.PingResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/pingRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/pingResponse")
    public String ping(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preregister", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Preregister")
    @ResponseWrapper(localName = "preregisterResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.PreregisterResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/preregisterRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/preregisterResponse")
    public String preregister(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preauthenticate", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Preauthenticate")
    @ResponseWrapper(localName = "preauthenticateResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.PreauthenticateResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/preauthenticateRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/preauthenticateResponse")
    public String preauthenticate(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preauthorize", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Preauthorize")
    @ResponseWrapper(localName = "preauthorizeResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.PreauthorizeResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/preauthorizeRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/preauthorizeResponse")
    public String preauthorize(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getkeysinfo", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Getkeysinfo")
    @ResponseWrapper(localName = "getkeysinfoResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.GetkeysinfoResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/getkeysinfoRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/getkeysinfoResponse")
    public String getkeysinfo(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatekeyinfo", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Updatekeyinfo")
    @ResponseWrapper(localName = "updatekeyinfoResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.UpdatekeyinfoResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/updatekeyinfoRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/updatekeyinfoResponse")
    public String updatekeyinfo(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deregister", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Deregister")
    @ResponseWrapper(localName = "deregisterResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.DeregisterResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/deregisterRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/deregisterResponse")
    public String deregister(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

    /**
     * 
     * @param svcinfo
     * @param payload
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://soap.skfs.strongauth.com/", className = "com.strongkey.skfs.soapstubs.RegisterResponse")
    @Action(input = "http://soap.skfs.strongauth.com/SKFSServlet/registerRequest", output = "http://soap.skfs.strongauth.com/SKFSServlet/registerResponse")
    public String register(
        @WebParam(name = "svcinfo", targetNamespace = "")
        String svcinfo,
        @WebParam(name = "payload", targetNamespace = "")
        String payload);

}
